import { SpeakingQuestionSet } from './types';

export const presetSpeakingSets: SpeakingQuestionSet[] = [
  {
    id: 'speaking-set-1',
    title: 'Technology & Artificial Intelligence in Modern Life',
    topic: 'Công nghệ & Trí tuệ nhân tạo',
    level: 'Trung cấp',
    badge: 'Forecast Q3',
    isNew: true,
    description: 'Bộ đề dự đoán xu hướng công nghệ số, thiết bị điện tử thông minh và tác động của AI đến công việc và học tập.',
    createdAt: '2026-08-01T08:00:00.000Z',
    part1Questions: [
      {
        id: 'set1-p1-q1',
        part: 1,
        topic: 'Technology',
        suggestedDurationSeconds: 30,
        text: 'How often do you use technology in your daily routine?',
        sampleAnswerBand8: 'To be completely honest, technology plays an indispensable role in my day-to-day life. From the moment my smartphone alarm goes off in the morning to using laptops for research and staying connected via instant messaging apps, I rely heavily on digital devices for both academic productivity and leisure.',
        collocations: ['play an indispensable role', 'day-to-day life', 'stay connected', 'academic productivity'],
        ideaHints: ['Frequency of use (morning to night)', 'Specific devices (smartphones, laptops)', 'Purposes (work, communication, entertainment)'],
      },
      {
        id: 'set1-p1-q2',
        part: 1,
        topic: 'Technology',
        suggestedDurationSeconds: 30,
        text: 'What is your favorite electronic device, and why?',
        sampleAnswerBand8: 'Without a shadow of a doubt, my tablet is my all-time favorite gadget. It strikes the perfect balance between portability and functionality, allowing me to annotate academic papers, sketch creative diagrams, and stream documentaries on the go.',
        collocations: ['without a shadow of a doubt', 'all-time favorite gadget', 'strike the perfect balance', 'portability and functionality'],
        ideaHints: ['Name of device', 'Key features (portability, screen size)', 'How it helps your lifestyle'],
      },
      {
        id: 'set1-p1-q3',
        part: 1,
        topic: 'Technology',
        suggestedDurationSeconds: 30,
        text: 'Do you think modern technology has made our lives easier or more complicated?',
        sampleAnswerBand8: 'I would argue that technology is a double-edged sword. While it has undoubtedly streamlined communication and automated mundane chores, the constant influx of notifications can sometimes induce digital fatigue and disrupt our work-life equilibrium.',
        collocations: ['double-edged sword', 'streamline communication', 'automated mundane chores', 'digital fatigue', 'work-life equilibrium'],
        ideaHints: ['Two sides of the coin', 'Benefits (speed, convenience)', 'Drawbacks (distractions, screen addiction)'],
      },
    ],
    part2CueCard: {
      id: 'set1-p2-card',
      topic: 'Technology',
      title: 'Describe an electronic device or application you find extremely useful',
      bulletPoints: [
        'What the device or application is',
        'How often you use it',
        'What features you find most helpful',
        'And explain why this technology makes a significant difference in your life',
      ],
      prepTimeSeconds: 60,
      speakingTimeSeconds: 120,
      sampleAnswerBand8: `Today I would like to talk about Notion, an all-in-one productivity application that has completely revolutionized the way I manage my academic workflow and daily schedules.

I first stumbled upon this software about two years ago when I was feeling overwhelmed by disjointed note-taking apps and messy paper notebooks. Since then, it has become an integral part of my morning routine, and I use it on a daily basis across my smartphone and laptop.

What makes Notion truly exceptional is its unparalleled customizability. Unlike traditional static word processors, it operates on modular blocks, which means I can seamlessly embed interactive Kanban boards, relational databases, to-do lists, and multimedia references into a single cohesive workspace. Furthermore, its real-time synchronization ensures that all my project deliverables and revisions are up to date no matter where I am.

The main reason why this application has made such a profound impact on my life is that it eliminates cognitive overload. Instead of wasting precious mental bandwidth trying to remember deadlines, everything is systematically archived in my digital second brain. In short, it has elevated my productivity to a whole new level.`,
      collocations: ['revolutionize workflow', 'stumble upon', 'integral part of my routine', 'unparalleled customizability', 'modular blocks', 'cognitive overload', 'digital second brain'],
      ideaHints: ['Hook & introduction of device/app', 'How you discovered it', 'Key unique features & customization', 'Deep personal impact on productivity & stress reduction'],
    },
    part3Questions: [
      {
        id: 'set1-p3-q1',
        part: 3,
        topic: 'Artificial Intelligence',
        suggestedDurationSeconds: 45,
        text: 'What impact might Artificial Intelligence have on traditional employment in the coming decade?',
        sampleAnswerBand8: 'In my view, Artificial Intelligence will fundamentally reshape the global labor market. While routine and repetitive clerical tasks are highly susceptible to automation, AI will also foster demand for specialized roles in machine learning supervision, data ethics, and creative problem-solving. Workers will inevitably need to upskill to remain competitive in an AI-driven economy.',
        collocations: ['fundamentally reshape', 'susceptible to automation', 'foster demand for', 'upskill to remain competitive'],
        ideaHints: ['Automation of repetitive jobs', 'Emergence of new tech-centric careers', 'The necessity of continuous upskilling'],
      },
      {
        id: 'set1-p3-q2',
        part: 3,
        topic: 'Technology & Privacy',
        suggestedDurationSeconds: 45,
        text: 'Should governments impose stricter regulations on tech companies regarding personal data privacy?',
        sampleAnswerBand8: 'Absolutely. Given the ubiquitous nature of big data harvesting and targeted algorithms, robust regulatory frameworks like GDPR are vital. Governments must mandate strict transparency and penalize unauthorized surveillance to safeguard citizens fundamental right to digital privacy.',
        collocations: ['ubiquitous nature', 'big data harvesting', 'robust regulatory frameworks', 'mandate strict transparency', 'safeguard digital privacy'],
        ideaHints: ['Current risks (data leaks, algorithmic tracking)', 'Need for legislation like GDPR', 'Balancing innovation with user protection'],
      },
      {
        id: 'set1-p3-q3',
        part: 3,
        topic: 'Technology & Human Relationships',
        suggestedDurationSeconds: 45,
        text: 'Do virtual interactions risk eroding face-to-face social bonds among young people?',
        sampleAnswerBand8: 'There is indeed a legitimate concern that excessive screen time might weaken deep interpersonal connections. While social media facilitates instantaneous communication across continents, it often fosters superficial interactions that lack emotional nuances and non-verbal cues inherent in genuine in-person conversations.',
        collocations: ['legitimate concern', 'excessive screen time', 'interpersonal connections', 'superficial interactions', 'non-verbal cues'],
        ideaHints: ['Breadth vs depth of online friendships', 'Absence of body language and genuine empathy', 'The risk of social isolation'],
      },
    ],
  },
  {
    id: 'speaking-set-2',
    title: 'Travel, Tourism & Memorable Journeys',
    topic: 'Du lịch & Khám phá văn hóa',
    level: 'Trung cấp',
    badge: 'Hot',
    isNew: true,
    description: 'Chủ đề quen thuộc nhưng hay gặp trong phòng thi IELTS: trải nghiệm du lịch đáng nhớ, du lịch bền vững và giao lưu văn hóa.',
    createdAt: '2026-08-05T09:00:00.000Z',
    part1Questions: [
      {
        id: 'set2-p1-q1',
        part: 1,
        topic: 'Travel',
        suggestedDurationSeconds: 30,
        text: 'Do you prefer traveling alone or with a group of friends?',
        sampleAnswerBand8: 'Personally, I have a strong preference for traveling with a close circle of friends. Exploring unfamiliar destinations together not only fosters collective memories but also provides a sense of security when navigating foreign public transit or language barriers.',
        collocations: ['strong preference for', 'close circle of friends', 'foster collective memories', 'sense of security', 'language barriers'],
        ideaHints: ['Preference stated clearly', 'Reasons (sharing moments, safety, cost splitting)', 'Comparison with solo travel'],
      },
      {
        id: 'set2-p1-q2',
        part: 1,
        topic: 'Travel',
        suggestedDurationSeconds: 30,
        text: 'What kind of places do you usually like to visit on vacation?',
        sampleAnswerBand8: 'I am particularly drawn to tranquil mountainous regions rich in natural biodiversity and heritage sites, rather than bustling cosmopolitan metropolises. Being surrounded by lush greenery and fresh air allows me to recharge my batteries after hectic work weeks.',
        collocations: ['particularly drawn to', 'tranquil mountainous regions', 'heritage sites', 'recharge my batteries', 'hectic work weeks'],
        ideaHints: ['Type of destinations (nature vs city)', 'Atmosphere & vibe', 'How it affects your wellbeing'],
      },
      {
        id: 'set2-p1-q3',
        part: 1,
        topic: 'Travel',
        suggestedDurationSeconds: 30,
        text: 'What is the most memorable souvenir you have ever bought while traveling?',
        sampleAnswerBand8: 'A few years back, while trekking through Sapa in northern Vietnam, I purchased a hand-embroidered tapestry from a local artisan. It is intricately woven with traditional ethnic patterns and serves as a timeless memento of that breathtaking adventure.',
        collocations: ['hand-embroidered tapestry', 'local artisan', 'intricately woven', 'timeless memento', 'breathtaking adventure'],
        ideaHints: ['Item name & origin', 'Craftsmanship / story behind it', 'Sentimental value'],
      },
    ],
    part2CueCard: {
      id: 'set2-p2-card',
      topic: 'Travel',
      title: 'Describe a memorable journey or trip you took that left a deep impression on you',
      bulletPoints: [
        'Where you went and who accompanied you',
        'How you traveled there',
        'What activities you engaged in during the trip',
        'And explain why this journey was so unforgettable for you',
      ],
      prepTimeSeconds: 60,
      speakingTimeSeconds: 120,
      sampleAnswerBand8: `I would like to recount an extraordinary road trip I embarked on with two of my closest college friends along the breathtaking coastal highway of Central Vietnam, specifically from Da Nang to Quy Nhon.

We set off on this adventure last summer on rented motorbikes, which allowed us the ultimate flexibility to stop whenever we encountered panoramic seascapes or secluded beaches. The entire route was mesmerizing, flanked by azure ocean waves on one side and majestic verdant mountains on the other.

During our three-day itinerary, we immersed ourselves in authentic local experiences. We woke up at dawn to witness bustling fish markets, savored fresh street delicacies like grilled seafood and savory pancakes, and engaged in deep conversations with hospitable fishermen. 

What truly cemented this trip in my memory was not merely the postcard-perfect vistas, but the profound sense of liberation it gave me. Cruising along the coastal breeze, far away from urban concrete jungles and academic anxieties, gave me a newfound appreciation for the simple beauty of nature and camaraderie.`,
      collocations: ['extraordinary road trip', 'embark on an adventure', 'panoramic seascapes', 'azure ocean waves', 'verdant mountains', 'immerse ourselves in authentic experiences', 'postcard-perfect vistas', 'profound sense of liberation', 'camaraderie'],
      ideaHints: ['Introduction of route and companions', 'Mode of transportation & scenic route', 'Authentic cultural & culinary activities', 'Emotional takeaway & philosophical reflection'],
    },
    part3Questions: [
      {
        id: 'set2-p3-q1',
        part: 3,
        topic: 'Tourism & Environment',
        suggestedDurationSeconds: 45,
        text: 'What environmental challenges can mass tourism cause for popular holiday destinations?',
        sampleAnswerBand8: 'Mass tourism often exerts enormous pressure on fragile ecosystems. The unchecked influx of visitors leads to severe plastic pollution, coral reef degradation from motorized water sports, and excessive depletion of local fresh water supplies. Without sustainable tourism policies, iconic destinations risk irreversible ecological damage.',
        collocations: ['exert enormous pressure on', 'fragile ecosystems', 'unchecked influx of visitors', 'coral reef degradation', 'sustainable tourism policies', 'irreversible ecological damage'],
        ideaHints: ['Pollution & waste management', 'Habitat destruction and wildlife disturbance', 'Depletion of natural resources'],
      },
      {
        id: 'set2-p3-q2',
        part: 3,
        topic: 'Cultural Exchange',
        suggestedDurationSeconds: 45,
        text: 'How does international travel foster mutual understanding among different cultures?',
        sampleAnswerBand8: 'Traveling abroad acts as a powerful antidote to prejudice and ethnocentrism. When individuals directly engage with local communities, sample traditional cuisines, and observe indigenous customs, they develop cultural empathy and realize that human aspirations are universally shared despite outward differences.',
        collocations: ['powerful antidote to prejudice', 'ethnocentrism', 'cultural empathy', 'indigenous customs', 'universally shared'],
        ideaHints: ['Breaking stereotypes and cultural barriers', 'Experiencing everyday life firsthand', 'Promoting tolerance and global citizenship'],
      },
      {
        id: 'set2-p3-q3',
        part: 3,
        topic: 'Future of Travel',
        suggestedDurationSeconds: 45,
        text: 'Do you believe virtual reality tours could ever replace real-world travel in the future?',
        sampleAnswerBand8: 'In my perspective, while virtual reality will undoubtedly serve as a convenient preview tool or an educational aid for those with mobility constraints, it can never fully replicate physical travel. The multi-sensory stimulation of tasting local cuisine, smelling the sea breeze, and sharing laughter with locals cannot be synthesized in a digital headset.',
        collocations: ['convenient preview tool', 'mobility constraints', 'replicate physical travel', 'multi-sensory stimulation', 'synthesized in a digital headset'],
        ideaHints: ['VR as an accessibility/preview tool', 'The irreplicable multi-sensory aspects of real travel', 'The spontaneous emotional human connection'],
      },
    ],
  },
  {
    id: 'speaking-set-3',
    title: 'Education, Books & Lifelong Learning',
    topic: 'Giáo dục & Đọc sách',
    level: 'Nâng cao',
    badge: 'Forecast Q4',
    isNew: true,
    description: 'Chủ đề học thuật chuyên sâu về văn hóa đọc, phương pháp tự học và sự chuyển dịch của nền giáo dục hiện đại.',
    createdAt: '2026-08-10T10:00:00.000Z',
    part1Questions: [
      {
        id: 'set3-p1-q1',
        part: 1,
        topic: 'Reading',
        suggestedDurationSeconds: 30,
        text: 'Do you prefer reading physical paper books or e-books?',
        sampleAnswerBand8: 'I must admit that I am an avid fan of tangible paper books. There is something uniquely gratifying about the tactile sensation of turning crisp pages and the faint smell of paper that digital screens simply fail to emulate.',
        collocations: ['avid fan of', 'tangible paper books', 'uniquely gratifying', 'tactile sensation', 'fail to emulate'],
        ideaHints: ['Sensory experience of physical books', 'Distraction-free reading', 'Portability of e-books as contrast'],
      },
      {
        id: 'set3-p1-q2',
        part: 1,
        topic: 'Education',
        suggestedDurationSeconds: 30,
        text: 'What was your favorite subject when you were in secondary school?',
        sampleAnswerBand8: 'Back in high school, I was thoroughly captivated by World History. Our teacher had a knack for weaving historical events into captivating narratives, which helped me comprehend the geopolitical roots of contemporary global issues.',
        collocations: ['thoroughly captivated by', 'have a knack for', 'captivating narratives', 'geopolitical roots', 'contemporary global issues'],
        ideaHints: ['Subject name', 'Teacher influence and teaching method', 'Long-term value of the subject'],
      },
      {
        id: 'set3-p1-q3',
        part: 1,
        topic: 'Learning',
        suggestedDurationSeconds: 30,
        text: 'How do you usually acquire new skills or knowledge outside of school?',
        sampleAnswerBand8: 'I predominantly rely on online open courseware and interactive platforms like Coursera and YouTube tutorials. They afford me the flexibility to learn self-paced while absorbing insights from leading industry practitioners.',
        collocations: ['predominantly rely on', 'online open courseware', 'self-paced learning', 'absorb insights', 'industry practitioners'],
        ideaHints: ['Digital resources & MOOCs', 'Self-directed learning', 'Practical application'],
      },
    ],
    part2CueCard: {
      id: 'set3-p2-card',
      topic: 'Books & Influence',
      title: 'Describe an insightful book that had a profound influence on your mindset',
      bulletPoints: [
        'What the title and genre of the book is',
        'When and why you decided to read it',
        'What main message or philosophy it conveyed',
        'And explain how this book transformed your perspective or habits',
      ],
      prepTimeSeconds: 60,
      speakingTimeSeconds: 120,
      sampleAnswerBand8: `The book that has exerted the most profound influence on my mindset is "Atomic Habits", written by the renowned author James Clear. It falls under the behavioral psychology and personal development genre.

I picked up this book about a year and a half ago during a period when I was struggling with chronic procrastination and erratic study routines. I was constantly seeking dramatic breakthroughs, but repeatedly burnt out.

The central thesis of the book is deceptively simple yet transformative: monumental changes are not the outcome of sporadic heroic efforts, but rather the cumulative compounding effect of tiny, 1% improvements made consistently over time. James Clear breaks down habit formation into a clear four-step loop—cue, craving, response, and reward—and emphasizes building identity-based habits rather than outcome-driven goals.

This paradigm shift thoroughly revamped my daily life. Instead of aiming to study for eight exhausting hours in one sitting, I started committing to twenty minutes of focused deliberate practice every single morning. Over the course of months, this compounding consistency helped me master IELTS vocabulary and maintain a healthy exercise regimen effortlessly.`,
      collocations: ['exert a profound influence', 'behavioral psychology', 'chronic procrastination', 'erratic routines', 'central thesis', 'cumulative compounding effect', 'identity-based habits', 'paradigm shift', 'deliberate practice'],
      ideaHints: ['Title & author introduction', 'Personal context & struggles before reading', 'Key psychological insights & 1% rule', 'Concrete behavioral transformations and habits formed'],
    },
    part3Questions: [
      {
        id: 'set3-p3-q1',
        part: 3,
        topic: 'Future of Education',
        suggestedDurationSeconds: 45,
        text: 'How might digital classrooms and AI tutors transform the traditional teacher-student relationship?',
        sampleAnswerBand8: 'AI-driven educational tools will shift the role of teachers from being the primary dispensers of knowledge to becoming empathetic mentors and facilitators. While intelligent tutoring systems can personalize grammar drills and grading at scale, human educators remain irreplaceable for fostering critical thinking, emotional resilience, and moral character.',
        collocations: ['dispensers of knowledge', 'empathetic mentors', 'intelligent tutoring systems', 'foster critical thinking', 'emotional resilience'],
        ideaHints: ['Personalized pace via AI', 'Shift of teacher role to coaching/mentoring', 'Irreplaceability of human emotional connection'],
      },
      {
        id: 'set3-p3-q2',
        part: 3,
        topic: 'Lifelong Learning',
        suggestedDurationSeconds: 45,
        text: 'Why has lifelong learning become essential in the modern 21st-century workforce?',
        sampleAnswerBand8: 'In an era characterized by rapid technological disruption and swift skills obsolescence, resting on ones laurels is no longer an option. Continuous professional development ensures that individuals remain agile, adaptable, and capable of pivoting into emerging multidisciplinary sectors.',
        collocations: ['technological disruption', 'skills obsolescence', 'rest on ones laurels', 'continuous professional development', 'remain agile and adaptable'],
        ideaHints: ['Speed of industry changes', 'Risk of skills becoming outdated', 'Career longevity and agility'],
      },
      {
        id: 'set3-p3-q3',
        part: 3,
        topic: 'Reading Habits',
        suggestedDurationSeconds: 45,
        text: 'Why do younger generations seem to read fewer long-form books compared to previous generations?',
        sampleAnswerBand8: 'The proliferation of short-form bite-sized video algorithms on platforms like TikTok has rewired our attention spans to crave immediate dopamine hits. Consequently, engaging in deep immersive reading, which demands sustained cognitive focus and patience, has become increasingly challenging for digital natives.',
        collocations: ['proliferation of short-form content', 'bite-sized video algorithms', 'rewire attention spans', 'immediate dopamine hits', 'sustained cognitive focus', 'digital natives'],
        ideaHints: ['Short-form media & diminished attention span', 'Instant gratification vs slow deep reading', 'Need for conscious digital detox'],
      },
    ],
  },
  {
    id: 'speaking-set-4',
    title: 'Environment, Climate Change & Green Living',
    topic: 'Môi trường & Lối sống xanh',
    level: 'Nâng cao',
    badge: 'Mới',
    isNew: true,
    description: 'Chủ đề thời sự toàn cầu: ô nhiễm đô thị, rác thải nhựa, biến đổi khí hậu và trách nhiệm của cá nhân & chính phủ.',
    createdAt: '2026-08-12T14:00:00.000Z',
    part1Questions: [
      {
        id: 'set4-p1-q1',
        part: 1,
        topic: 'Weather & Nature',
        suggestedDurationSeconds: 30,
        text: 'What kind of weather do you enjoy the most?',
        sampleAnswerBand8: 'I have always had a penchant for crisp autumn weather, characterized by mild temperatures and gentle breezes. It is the ideal climate for outdoor strolls and outdoor coffee sessions without suffering from oppressive heat or freezing humidity.',
        collocations: ['have a penchant for', 'crisp autumn weather', 'mild temperatures', 'gentle breezes', 'oppressive heat'],
        ideaHints: ['Preferred season/weather', 'Sensory description', 'Favorite activities in that weather'],
      },
      {
        id: 'set4-p1-q2',
        part: 1,
        topic: 'Recycling',
        suggestedDurationSeconds: 30,
        text: 'Do you practice waste sorting or recycling at home?',
        sampleAnswerBand8: 'Yes, absolutely. In my household, we make a conscious effort to segregate organic food scraps from recyclable materials such as plastic bottles, cardboard packaging, and aluminum cans. We also repurpose grocery bags to minimize single-use waste.',
        collocations: ['conscious effort', 'segregate organic scraps', 'recyclable materials', 'repurpose grocery bags', 'single-use waste'],
        ideaHints: ['Household habits', 'Types of waste separated', 'Environmental awareness'],
      },
      {
        id: 'set4-p1-q3',
        part: 1,
        topic: 'Green Spaces',
        suggestedDurationSeconds: 30,
        text: 'Are there enough public parks and green spaces in your neighborhood?',
        sampleAnswerBand8: 'Regrettably, my urban residential area is rather densely populated, with high-rise apartment complexes overshadowing small municipal parks. I believe municipal authorities should allocate more urban land to cultivate botanical gardens and recreational green lungs.',
        collocations: ['densely populated', 'high-rise apartment complexes', 'municipal authorities', 'recreational green lungs'],
        ideaHints: ['Current state of green spaces', 'Impact on local residents', 'Recommendation for city planning'],
      },
    ],
    part2CueCard: {
      id: 'set4-p2-card',
      topic: 'Environment',
      title: 'Describe an environmental issue in your city that concerns you deeply',
      bulletPoints: [
        'What the environmental issue is',
        'What causes this problem',
        'How it impacts the daily lives and health of local residents',
        'And suggest what measures could be implemented to tackle it',
      ],
      prepTimeSeconds: 60,
      speakingTimeSeconds: 120,
      sampleAnswerBand8: `The environmental crisis that causes me the greatest distress in my city is hazardous ambient air pollution, predominantly caused by fine particulate matter known as PM2.5.

During dry winter months, the entire skyline is frequently engulfed in a thick blanket of toxic smog. The primary culprits behind this phenomenon are twofold: first, the overwhelming volume of motorized fossil-fuel vehicles on congested roads, and second, uncontained dust from relentless construction sites and industrial emissions in peripheral districts.

The repercussions on public health are alarming. An increasing number of young children and elderly citizens suffer from acute respiratory ailments, chronic bronchitis, and eye irritation. On severe air quality warning days, outdoor physical activities are severely curtailed, diminishing our overall quality of life.

To alleviate this crisis, a multifaceted strategy is imperative. The municipal government ought to invest heavily in clean public transit infrastructure like electric metro lines and impose strict emission quotas on industrial factories. Concurrently, citizens should be encouraged to transition toward electric scooters and participate in urban tree-planting initiatives.`,
      collocations: ['hazardous ambient air pollution', 'fine particulate matter', 'engulfed in toxic smog', 'primary culprits', 'uncontained dust', 'acute respiratory ailments', 'diminish quality of life', 'multifaceted strategy', 'clean public transit infrastructure'],
      ideaHints: ['Identify specific issue (PM2.5 smog)', 'Root causes (traffic & construction)', 'Direct health repercussions on vulnerable groups', 'Holistic solutions from both government & citizens'],
    },
    part3Questions: [
      {
        id: 'set4-p3-q1',
        part: 3,
        topic: 'Global Responsibility',
        suggestedDurationSeconds: 45,
        text: 'Should individual lifestyle changes or government legislation take priority in combating climate change?',
        sampleAnswerBand8: 'While grassroots citizen initiatives like reducing single-use plastic and conserving electricity are admirable, sweeping government policy is far more impactful. Only stringent environmental regulations, carbon taxes, and renewable energy subsidies can compel multinational corporations to decarbonize industrial supply chains at the necessary scale.',
        collocations: ['grassroots citizen initiatives', 'sweeping government policy', 'stringent environmental regulations', 'carbon taxes', 'renewable energy subsidies', 'decarbonize supply chains'],
        ideaHints: ['Role of individual habits', 'Scale and power of government legislation', 'Corporate accountability'],
      },
      {
        id: 'set4-p3-q2',
        part: 3,
        topic: 'Renewable Energy',
        suggestedDurationSeconds: 45,
        text: 'What are the main hurdles preventing developing nations from transitioning to 100% clean renewable energy?',
        sampleAnswerBand8: 'The foremost obstacle is the exorbitant upfront capital expenditure required to establish solar, wind, and smart grid infrastructure. Furthermore, many developing economies rely heavily on affordable fossil fuel reserves to maintain rapid industrial growth, making a sudden transition economically disruptive without international green climate financing.',
        collocations: ['exorbitant upfront capital', 'smart grid infrastructure', 'affordable fossil fuel reserves', 'economically disruptive', 'green climate financing'],
        ideaHints: ['High initial investment costs', 'Energy security and economic growth priorities', 'Need for global financial & technological transfer'],
      },
      {
        id: 'set4-p3-q3',
        part: 3,
        topic: 'Future Outlook',
        suggestedDurationSeconds: 45,
        text: 'Are you optimistic or pessimistic about the future of our planet in the next 50 years?',
        sampleAnswerBand8: 'I maintain a stance of cautious optimism. While escalating global temperatures and climate anomalies are deeply concerning, the unprecedented global mobilization of youth climate activists, coupled with exponential advancements in fusion energy and green hydrogen, gives me hope that humanity will pivot in time to avert catastrophe.',
        collocations: ['cautious optimism', 'climate anomalies', 'unprecedented global mobilization', 'exponential advancements', 'avert catastrophe'],
        ideaHints: ['Acknowledge alarming realities', 'Highlight promising technological & youth-led breakthroughs', 'Call for urgency'],
      },
    ],
  },
  {
    id: 'speaking-set-5',
    title: 'Food, Culinary Heritage & Healthy Living',
    topic: 'Ẩm thực, Dinh dưỡng & Sức khỏe',
    level: 'Cơ bản',
    badge: 'Hot',
    isNew: false,
    description: 'Chủ đề gần gũi, nhiều từ vựng về thói quen ăn uống, món ăn truyền thống và phong cách sống cân bằng.',
    createdAt: '2026-08-14T08:00:00.000Z',
    part1Questions: [
      {
        id: 'set5-p1-q1',
        part: 1,
        topic: 'Cooking',
        suggestedDurationSeconds: 30,
        text: 'Do you know how to cook, and how often do you prepare meals?',
        sampleAnswerBand8: 'Yes, I would consider myself reasonably competent in the kitchen. I usually prepare home-cooked meals four to five times a week, as it allows me to control nutritional ingredients and unwind creatively after demanding work sessions.',
        collocations: ['reasonably competent', 'home-cooked meals', 'nutritional ingredients', 'unwind creatively'],
        ideaHints: ['Cooking skill level', 'Frequency of cooking', 'Benefits for health & mental relaxation'],
      },
      {
        id: 'set5-p1-q2',
        part: 1,
        topic: 'Food Preference',
        suggestedDurationSeconds: 30,
        text: 'What is your favorite comfort food when you feel stressed?',
        sampleAnswerBand8: 'Whenever I am feeling down or stressed out, a steaming bowl of traditional Vietnamese beef Pho is my ultimate comfort meal. The aromatic broth infused with cinnamon, star anise, and fresh herbs always works wonders in lifting my spirits.',
        collocations: ['steaming bowl', 'ultimate comfort meal', 'aromatic broth', 'fresh herbs', 'lift my spirits'],
        ideaHints: ['Specific dish', 'Sensory flavors and aromas', 'Emotional soothing effect'],
      },
      {
        id: 'set5-p1-q3',
        part: 1,
        topic: 'Eating Habits',
        suggestedDurationSeconds: 30,
        text: 'Do you think young people in your country eat healthier food than before?',
        sampleAnswerBand8: 'It is somewhat polarized. On one hand, fitness awareness has spurred a trend toward clean eating and plant-based diets. On the other hand, the widespread convenience of fast-food delivery apps has led many busy urbanites to consume excessive refined sugars and processed fats.',
        collocations: ['somewhat polarized', 'fitness awareness', 'clean eating', 'plant-based diets', 'busy urbanites', 'refined sugars'],
        ideaHints: ['Two conflicting trends', 'Growing health consciousness vs fast food convenience'],
      },
    ],
    part2CueCard: {
      id: 'set5-p2-card',
      topic: 'Culinary Heritage',
      title: 'Describe a traditional dish from your country that you would recommend to a foreigner',
      bulletPoints: [
        'What the dish is and its key ingredients',
        'How it is prepared and served',
        'When people typically eat it',
        'And explain why this dish is a cultural masterpiece of your nation',
      ],
      prepTimeSeconds: 60,
      speakingTimeSeconds: 120,
      sampleAnswerBand8: `If I had the pleasure of introducing a foreign visitor to Vietnamese gastronomy, I would without hesitation recommend Banh Mi, our world-renowned street food sandwich that perfectly encapsulates our culinary ingenuity.

At first glance, Banh Mi may appear to be a humble baguette, but its brilliance lies in the harmonious contrast of textures and flavors. The bread itself boasts an ultra-crispy golden crust with an airy, feather-light crumb. It is generously slathered with rich pork liver pâté and homemade mayonnaise, then stuffed with savory slices of roasted pork belly, Vietnamese cold cuts, and succulent meatballs.

What elevates Banh Mi to a culinary masterpiece is the delicate counterbalance provided by crunchy pickled daikon and carrots, fresh cucumber strips, and fragrant sprigs of cilantro, all drizzled with a dash of savory chili sauce.

This dish represents a fascinating historical synthesis of French colonial baking techniques and vibrant Vietnamese culinary philosophy. It is eaten for breakfast, lunch, or late-night snacks across every street corner, offering an explosion of savory, tangy, and spicy sensations in every single bite.`,
      collocations: ['culinary ingenuity', 'harmonious contrast of textures', 'ultra-crispy golden crust', 'pork liver pâté', 'culinary masterpiece', 'delicate counterbalance', 'historical synthesis', 'explosion of sensations'],
      ideaHints: ['Introduction of Banh Mi & global prestige', 'Detailed breakdown of ingredients & textures', 'The secret balance of herbs & pickled veggies', 'Cultural & historical significance'],
    },
    part3Questions: [
      {
        id: 'set5-p3-q1',
        part: 3,
        topic: 'Food & Globalization',
        suggestedDurationSeconds: 45,
        text: 'How has globalization influenced eating habits and traditional culinary cultures worldwide?',
        sampleAnswerBand8: 'Globalization has led to a fascinating fusion of international culinary styles, making exotic ingredients and foreign cuisines accessible to ordinary consumers. However, the downside is the homogenization of food cultures, where ubiquitous international fast-food chains threaten to overshadow time-honored artisanal cooking practices.',
        collocations: ['fascinating fusion', 'accessible to ordinary consumers', 'homogenization of food cultures', 'time-honored artisanal practices'],
        ideaHints: ['Access to global cuisine & culinary experimentation', 'Risk of cultural homogenization and loss of authentic cooking traditions'],
      },
      {
        id: 'set5-p3-q2',
        part: 3,
        topic: 'Health & Government',
        suggestedDurationSeconds: 45,
        text: 'Should governments impose a tax on sugary beverages and junk food to curb obesity rates?',
        sampleAnswerBand8: 'In my view, implementing a sugar tax is a sensible public health intervention. High-sugar sodas and ultra-processed snacks impose a severe long-term burden on national healthcare budgets due to diabetes and cardiovascular diseases. Revenue generated from such taxes should be directly reinvested into subsidizing fresh agricultural produce and school nutrition programs.',
        collocations: ['public health intervention', 'ultra-processed snacks', 'cardiovascular diseases', 'subsidizing fresh produce', 'nutrition programs'],
        ideaHints: ['Economic deterrent against unhealthy habits', 'Reducing healthcare strain', 'Reinvesting tax revenues into healthy food subsidies'],
      },
      {
        id: 'set5-p3-q3',
        part: 3,
        topic: 'Food Waste',
        suggestedDurationSeconds: 45,
        text: 'What can supermarkets and restaurants do to minimize large-scale food waste?',
        sampleAnswerBand8: 'Commercial food establishments should adopt dynamic inventory algorithms to predict consumer demand accurately. Furthermore, surplus unsold food that remains safe for consumption should be channeled to local food banks and charitable shelters, while unavoidable organic waste can be converted into bio-fertilizer rather than dumped in landfills.',
        collocations: ['dynamic inventory algorithms', 'surplus unsold food', 'charitable shelters', 'bio-fertilizer', 'dumped in landfills'],
        ideaHints: ['Technological demand forecasting', 'Donating surplus edible food to food banks', 'Composting and circular economy solutions'],
      },
    ],
  },
];
