import { VideoItem, VideoSegment, VideoQuizQuestion } from './types';

export const presetVideos: VideoItem[] = [
  {
    id: 'vid-steve-jobs',
    sourceType: 'youtube',
    youtubeId: 'UF8uR6Z6KLc',
    title: 'Steve Jobs\' 2005 Stanford Commencement Address (Trích đoạn truyền cảm hứng)',
    thumbnailUrl: 'https://img.youtube.com/vi/UF8uR6Z6KLc/hqdefault.jpg',
    durationSeconds: 180,
    category: 'Cảm hứng & Lãnh đạo',
    level: 'Trung cấp',
    status: 'ready',
    segmentsCount: 6,
    completedSegmentsCount: 2,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'vid-ielts-speaking',
    sourceType: 'youtube',
    youtubeId: 'sRFEVpr1GzU',
    title: 'IELTS Speaking Band 9.0 - Bài mẫu chủ đề Công nghệ & Tương lai',
    thumbnailUrl: 'https://img.youtube.com/vi/sRFEVpr1GzU/hqdefault.jpg',
    durationSeconds: 240,
    category: 'Luyện thi IELTS',
    level: 'Nâng cao',
    status: 'ready',
    segmentsCount: 6,
    completedSegmentsCount: 1,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'vid-business-pitch',
    sourceType: 'youtube',
    youtubeId: 'wT3t59O6_7Q',
    title: 'Tiếng Anh Giao Tiếp Kinh Doanh - Thuyết Phục Đối Tác & Đàm Phán',
    thumbnailUrl: 'https://img.youtube.com/vi/wT3t59O6_7Q/hqdefault.jpg',
    durationSeconds: 210,
    category: 'Giao tiếp Thương mại',
    level: 'Trung cấp',
    status: 'ready',
    segmentsCount: 5,
    completedSegmentsCount: 0,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'vid-daily-conversation',
    sourceType: 'youtube',
    youtubeId: 'bgfdqVmVjfk',
    title: 'Học Tiếng Anh Hàng Ngày - Gọi Món Tại Nhà Hàng Sang Trọng',
    thumbnailUrl: 'https://img.youtube.com/vi/bgfdqVmVjfk/hqdefault.jpg',
    durationSeconds: 150,
    category: 'Giao tiếp Hàng ngày',
    level: 'Sơ cấp',
    status: 'ready',
    segmentsCount: 5,
    completedSegmentsCount: 0,
    createdAt: new Date().toISOString(),
  },
];

export const presetVideoSegments: Record<string, VideoSegment[]> = {
  'vid-steve-jobs': [
    {
      id: 'seg-sj-1',
      videoId: 'vid-steve-jobs',
      orderIndex: 1,
      startTime: 12,
      endTime: 18,
      textEn: 'I am honored to be with you today at your commencement from one of the finest universities in the world.',
      ipa: '/aɪ æm ˈɒnəd tuː biː wɪð juː təˈdeɪ æt jɔː kəˈmɛnsmənt frɒm wʌn ɒv ðə ˈfaɪnɪst ˌjuːnɪˈvɜːsɪtiːz ɪn ðə wɜːld/',
      translationVi: 'Tôi rất vinh hạnh được có mặt cùng các bạn hôm nay trong lễ tốt nghiệp tại một trong những trường đại học tốt nhất thế giới.',
    },
    {
      id: 'seg-sj-2',
      videoId: 'vid-steve-jobs',
      orderIndex: 2,
      startTime: 19,
      endTime: 25,
      textEn: 'Today I want to tell you three stories from my life. That\'s it. No big deal. Just three stories.',
      ipa: '/təˈdeɪ aɪ wɒnt tuː tɛl juː θriː ˈstɔːriːz frɒm maɪ laɪf. ðæt s ɪt. nəʊ bɪɡ diːl. ʤʌst θriː ˈstɔːriːz/',
      translationVi: 'Hôm nay tôi muốn kể cho các bạn nghe ba câu chuyện từ cuộc đời tôi. Chỉ có thế thôi. Không có gì to tát. Chỉ ba câu chuyện.',
    },
    {
      id: 'seg-sj-3',
      videoId: 'vid-steve-jobs',
      orderIndex: 3,
      startTime: 26,
      endTime: 34,
      textEn: 'The first story is about connecting the dots. You can\'t connect the dots looking forward; you can only connect them looking backward.',
      ipa: '/ðə fɜːst ˈstɔːri ɪz əˈbaʊt kəˈnɛktɪŋ ðə dɒts. juː kɑːnt kəˈnɛkt ðə dɒts ˈlʊkɪŋ ˈfɔːwəd; juː kæn ˈəʊnli kəˈnɛkt ðɛm ˈlʊkɪŋ ˈbækwəd/',
      translationVi: 'Câu chuyện đầu tiên là về việc kết nối các điểm mốc. Bạn không thể kết nối các điểm mốc khi nhìn về tương lai; bạn chỉ có thể kết nối chúng khi nhìn lại quá khứ.',
    },
    {
      id: 'seg-sj-4',
      videoId: 'vid-steve-jobs',
      orderIndex: 4,
      startTime: 35,
      endTime: 42,
      textEn: 'So you have to trust that the dots will somehow connect in your future. You have to trust in something.',
      ipa: '/səʊ juː hæv tuː trʌst ðæt ðə dɒts wɪl ˈsʌmhaʊ kəˈnɛkt ɪn jɔː ˈfjuːʧə. juː hæv tuː trʌst ɪn ˈsʌmθɪŋ/',
      translationVi: 'Vì vậy bạn phải tin tưởng rằng các điểm mốc sẽ kết nối với nhau theo một cách nào đó trong tương lai. Bạn phải tin vào một điều gì đó.',
    },
    {
      id: 'seg-sj-5',
      videoId: 'vid-steve-jobs',
      orderIndex: 5,
      startTime: 43,
      endTime: 51,
      textEn: 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.',
      ipa: '/jɔː wɜːk ɪz ˈɡəʊɪŋ tuː fɪl ə lɑːʤ pɑːt ɒv jɔː laɪf, ænd ðə ˈəʊnli weɪ tuː biː ˈtruːli ˈsætɪsfaɪd ɪz tuː duː wɒt juː bɪˈliːv ɪz ɡreɪt wɜːk/',
      translationVi: 'Công việc sẽ chiếm một phần lớn trong cuộc đời bạn, và cách duy nhất để thực sự hài lòng là làm những gì bạn tin là công việc tuyệt vời.',
    },
    {
      id: 'seg-sj-6',
      videoId: 'vid-steve-jobs',
      orderIndex: 6,
      startTime: 52,
      endTime: 60,
      textEn: 'Stay Hungry. Stay Foolish. Thank you all very much.',
      ipa: '/steɪ ˈhʌŋɡri. steɪ ˈfuːlɪʃ. θæŋk juː ɔːl ˈvɛri mʌʧ/',
      translationVi: 'Hãy luôn khao khát. Hãy luôn dại khờ. Cảm ơn tất cả các bạn rất nhiều.',
    },
  ],
  'vid-ielts-speaking': [
    {
      id: 'seg-ielts-1',
      videoId: 'vid-ielts-speaking',
      orderIndex: 1,
      startTime: 5,
      endTime: 12,
      textEn: 'Artificial intelligence is rapidly transforming the way we process information and interact with technology.',
      ipa: '/ˌɑːtɪˈfɪʃəl ɪnˈtɛlɪʤəns ɪz ˈræpɪdli trænsˈfɔːmɪŋ ðə weɪ wiː ˈprəʊsɛs ˌɪnfəˈmeɪʃən ænd ˌɪntərˈækt wɪð tɛkˈnɒləʤi/',
      translationVi: 'Trí tuệ nhân tạo đang nhanh chóng thay đổi cách chúng ta xử lý thông tin và tương tác với công nghệ.',
    },
    {
      id: 'seg-ielts-2',
      videoId: 'vid-ielts-speaking',
      orderIndex: 2,
      startTime: 13,
      endTime: 20,
      textEn: 'From my perspective, automation will enhance human productivity rather than completely replace skilled workers.',
      ipa: '/frɒm maɪ pəˈspɛktɪv, ˌɔːtəˈmeɪʃən wɪl ɪnˈhɑːns ˈhjuːmən ˌprɒdʌkˈtɪvɪti ˈrɑːðə ðæn kəmˈpliːtli rɪˈpleɪs skɪld ˈwɜːkəz/',
      translationVi: 'Theo góc nhìn của tôi, tự động hóa sẽ nâng cao năng suất của con người chứ không thay thế hoàn toàn người lao động có tay nghề.',
    },
    {
      id: 'seg-ielts-3',
      videoId: 'vid-ielts-speaking',
      orderIndex: 3,
      startTime: 21,
      endTime: 29,
      textEn: 'Furthermore, educational institutions ought to adapt their curricula to emphasize creative critical thinking.',
      ipa: '/ˈfɜːðəmɔː, ˌɛdjuːˈkeɪʃənl ˌɪnstɪˈtjuːʃənz ɔːt tuː əˈdæpt ðeə kəˈrɪkjʊlə tuː ˈɛmfəsaɪz kriːˈeɪtɪv ˈkrɪtɪkəl ˈθɪŋkɪŋ/',
      translationVi: 'Hơn nữa, các cơ sở giáo dục nên điều chỉnh chương trình giảng dạy để nhấn mạnh vào tư duy phản biện sáng tạo.',
    },
    {
      id: 'seg-ielts-4',
      videoId: 'vid-ielts-speaking',
      orderIndex: 4,
      startTime: 30,
      endTime: 37,
      textEn: 'This approach ensures that future generations remain competitive in an increasingly digital global economy.',
      ipa: '/ðɪs əˈprəʊʧ ɪnˈʃʊəz ðæt ˈfjuːʧə ˌʤɛnəˈreɪʃənz rɪˈmeɪn kəmˈpɛtɪtɪv ɪn æn ɪnˈkriːsɪŋli ˈdɪʤɪtl ˈɡləʊbəl iːˈkɒnəmi/',
      translationVi: 'Cách tiếp cận này đảm bảo rằng các thế hệ tương lai duy trì khả năng cạnh tranh trong một nền kinh tế toàn cầu ngày càng số hóa.',
    },
    {
      id: 'seg-ielts-5',
      videoId: 'vid-ielts-speaking',
      orderIndex: 5,
      startTime: 38,
      endTime: 45,
      textEn: 'In conclusion, embracing modern technological advancements is indispensable for sustainable social progress.',
      ipa: '/ɪn kənˈkluːʒən, ɪmˈbreɪsɪŋ ˈmɒdən ˌtɛknəˈlɒʤɪkəl ədˈvɑːnsmənts ɪz ˌɪndɪsˈpɛnsəbl fɔː səˈsteɪnəbl ˈsəʊʃəl ˈprəʊɡrəs/',
      translationVi: 'Tóm lại, việc đón nhận các tiến bộ công nghệ hiện đại là không thể thiếu đối với sự phát triển xã hội bền vững.',
    },
    {
      id: 'seg-ielts-6',
      videoId: 'vid-ielts-speaking',
      orderIndex: 6,
      startTime: 46,
      endTime: 54,
      textEn: 'Thank you for your attention, I look forward to addressing any further questions you may have.',
      ipa: '/θæŋk juː fɔː jɔː əˈtɛnʃən, aɪ lʊk ˈfɔːwəd tuː əˈdrɛsɪŋ ˈɛni ˈfɜːðə ˈkwɛsʧənz juː meɪ hæv/',
      translationVi: 'Cảm ơn sự chú ý của bạn, tôi rất mong được giải đáp bất kỳ câu hỏi nào tiếp theo của bạn.',
    },
  ],
  'vid-business-pitch': [
    {
      id: 'seg-bp-1',
      videoId: 'vid-business-pitch',
      orderIndex: 1,
      startTime: 8,
      endTime: 15,
      textEn: 'Good morning everyone, today I would like to present our strategic expansion plan for the Asian market.',
      ipa: '/ɡʊd ˈmɔːnɪŋ ˈɛvrɪwʌn, təˈdeɪ aɪ wʊd laɪk tuː prɪˈzɛnt ˈaʊə strəˈtiːʤɪk ɪksˈpænʃən plæn fɔː ðə ˈeɪʃən ˈmɑːkɪt/',
      translationVi: 'Xin chào buổi sáng mọi người, hôm nay tôi xin trình bày kế hoạch mở rộng chiến lược của chúng tôi cho thị trường châu Á.',
    },
    {
      id: 'seg-bp-2',
      videoId: 'vid-business-pitch',
      orderIndex: 2,
      startTime: 16,
      endTime: 23,
      textEn: 'Our innovative SaaS solution has demonstrated a forty percent increase in operational efficiency.',
      ipa: '/ˈaʊər ɪnˈnɒvətɪv sæs səˈluːʃən hæz ˈdɛmənstreɪtɪd ə ˈfɔːti pəˈsɛnt ɪnˈkriːs ɪn ˌɒpəˈreɪʃənl ɪˈfɪʃənsi/',
      translationVi: 'Giải pháp SaaS sáng tạo của chúng tôi đã chứng minh mức tăng 40% về hiệu quả vận hành.',
    },
    {
      id: 'seg-bp-3',
      videoId: 'vid-business-pitch',
      orderIndex: 3,
      startTime: 24,
      endTime: 31,
      textEn: 'We are currently seeking a strategic investment of two million dollars to scale our operations.',
      ipa: '/wiː ɑː ˈkʌrəntli ˈsiːkɪŋ ə strəˈtiːʤɪk ɪnˈvɛstmənt ɒv tuː ˈmɪljən ˈdɒləz tuː skeɪl ˈaʊər ˌɒpəˈreɪʃənz/',
      translationVi: 'Chúng tôi hiện đang tìm kiếm khoản đầu tư chiến lược trị giá 2 triệu đô la để mở rộng quy mô hoạt động.',
    },
    {
      id: 'seg-bp-4',
      videoId: 'vid-business-pitch',
      orderIndex: 4,
      startTime: 32,
      endTime: 39,
      textEn: 'By partnering with us, you will gain exclusive access to a rapidly growing consumer base.',
      ipa: '/baɪ ˈpɑːtnərɪŋ wɪð ʌs, juː wɪl ɡeɪn ɪksˈkluːsɪv ˈæksɛs tuː ə ˈræpɪdli ˈɡrəʊɪŋ kənˈsjuːmə beɪs/',
      translationVi: 'Bằng việc hợp tác với chúng tôi, bạn sẽ có quyền truy cập độc quyền vào tập khách hàng tiêu dùng đang tăng trưởng nhanh chóng.',
    },
    {
      id: 'seg-bp-5',
      videoId: 'vid-business-pitch',
      orderIndex: 5,
      startTime: 40,
      endTime: 48,
      textEn: 'Let\'s negotiate a mutually beneficial deal that maximizes return on investment for both parties.',
      ipa: '/lɛts nɪˈɡəʊʃɪeɪt ə ˈmjuːʧʊəli ˌbɛnɪˈfɪʃəl diːl ðæt ˈmæksɪmaɪzɪz rɪˈtɜːn ɒn ɪnˈvɛstmənt fɔː bəʊθ ˈpɑːtiːz/',
      translationVi: 'Hãy đàm phán một thỏa thuận có lợi cho cả hai bên nhằm tối đa hóa lợi nhuận đầu tư.',
    },
  ],
  'vid-daily-conversation': [
    {
      id: 'seg-dc-1',
      videoId: 'vid-daily-conversation',
      orderIndex: 1,
      startTime: 5,
      endTime: 10,
      textEn: 'Good evening! Welcome to Bella Italia. Do you have a reservation under your name?',
      ipa: '/ɡʊd ˈiːvnɪŋ! ˈwɛlkəm tuː ˈbɛlə ɪˈtæliə. duː juː hæv ə ˌrɛzəˈveɪʃən ˈʌndə jɔː neɪm/',
      translationVi: 'Chào buổi tối! Chào mừng quý khách đến với Bella Italia. Quý khách có đặt bàn trước không ạ?',
    },
    {
      id: 'seg-dc-2',
      videoId: 'vid-daily-conversation',
      orderIndex: 2,
      startTime: 11,
      endTime: 17,
      textEn: 'Yes, I booked a table for two near the window at seven o\'clock under the name Smith.',
      ipa: '/jɛs, aɪ bʊkt ə ˈteɪbl fɔː tuː nɪə ðə ˈwɪndəʊ æt ˈsɛvn əˈklɒk ˈʌndə ðə neɪm smɪθ/',
      translationVi: 'Vâng, tôi có đặt một bàn cho hai người gần cửa sổ lúc 7 giờ tối dưới tên Smith.',
    },
    {
      id: 'seg-dc-3',
      videoId: 'vid-daily-conversation',
      orderIndex: 3,
      startTime: 18,
      endTime: 24,
      textEn: 'Right this way, please. Here are your menus. Can I start you off with something to drink?',
      ipa: '/raɪt ðɪs weɪ, pliːz. hɪər ɑː jɔː ˈmɛnjuːz. kæn aɪ stɑːt juː ɒf wɪð ˈsʌmθɪŋ tuː drɪŋk/',
      translationVi: 'Mời đi hướng này ạ. Đây là thực đơn của quý khách. Tôi có thể lấy đồ uống gì cho quý khách trước không?',
    },
    {
      id: 'seg-dc-4',
      videoId: 'vid-daily-conversation',
      orderIndex: 4,
      startTime: 25,
      endTime: 31,
      textEn: 'We would like a bottle of sparkling water and two glasses of house red wine, please.',
      ipa: '/wiː wʊd laɪk ə ˈbɒtl ɒv ˈspɑːklɪŋ ˈwɔːtər ænd tuː ˈɡlɑːsɪz ɒv haʊs rɛd waɪn, pliːz/',
      translationVi: 'Chúng tôi muốn một chai nước khoáng sủi bọt và hai ly rượu vang đỏ của nhà hàng, cảm ơn.',
    },
    {
      id: 'seg-dc-5',
      videoId: 'vid-daily-conversation',
      orderIndex: 5,
      startTime: 32,
      endTime: 39,
      textEn: 'Excellent choice. I will bring your drinks shortly while you decide on your main courses.',
      ipa: '/ˈɛksələnt ʧɔɪs. aɪ wɪl brɪŋ jɔː drɪŋks ˈʃɔːtli waɪl juː dɪˈsaɪd ɒn jɔː meɪn ˈkɔːsɪz/',
      translationVi: 'Lựa chọn tuyệt vời. Tôi sẽ mang đồ uống lên ngay trong lúc quý khách xem món chính.',
    },
  ],
};

export const presetVideoQuizzes: Record<string, VideoQuizQuestion[]> = {
  'vid-steve-jobs': [
    {
      id: 'quiz-sj-1',
      videoId: 'vid-steve-jobs',
      segmentId: 'seg-sj-1',
      type: 'meaning',
      question: 'Từ "commencement" trong đoạn văn có nghĩa là gì?',
      options: ['Lễ kỷ niệm thành lập', 'Lễ tốt nghiệp đại học', 'Cuộc thi thể thao', 'Lễ khai giảng khóa mới'],
      correctAnswerIndex: 1,
      explanation: 'Commencement có nghĩa là lễ tốt nghiệp đại học (graduation ceremony).',
    },
    {
      id: 'quiz-sj-2',
      videoId: 'vid-steve-jobs',
      segmentId: 'seg-sj-3',
      type: 'fill-in-the-blank',
      question: 'Điền từ còn thiếu: "You can\'t connect the dots looking _______; you can only connect them looking _______."',
      options: ['backward / forward', 'forward / backward', 'upward / downward', 'inward / outward'],
      correctAnswerIndex: 1,
      explanation: 'Steve Jobs nói: "You can\'t connect the dots looking forward; you can only connect them looking backward."',
    },
    {
      id: 'quiz-sj-3',
      videoId: 'vid-steve-jobs',
      segmentId: 'seg-sj-6',
      type: 'vocabulary',
      question: 'Cụm từ nổi tiếng "Stay Hungry. Stay Foolish." mang ý nghĩa gì?',
      options: ['Hãy luôn đói bụng và dại khờ', 'Hãy luôn khát khao học hỏi và không ngại ngần dại khờ', 'Hãy sống tiết kiệm và giản dị', 'Hãy tránh xa những điều nguy hiểm'],
      correctAnswerIndex: 1,
      explanation: 'Đây là thông điệp khuyên hãy luôn giữ tinh thần khao khát tri thức và dám thử thách bản thân.',
    },
  ],
  'vid-ielts-speaking': [
    {
      id: 'quiz-ielts-1',
      videoId: 'vid-ielts-speaking',
      segmentId: 'seg-ielts-1',
      type: 'meaning',
      question: 'Cụm từ "Artificial intelligence" có nghĩa là gì?',
      options: ['Trí tuệ nhân tạo', 'Công nghệ tự động', 'Mạng máy tính toàn cầu', 'Hệ thống thông tin số'],
      correctAnswerIndex: 0,
      explanation: 'Artificial intelligence (AI) có nghĩa là Trí tuệ nhân tạo.',
    },
    {
      id: 'quiz-ielts-2',
      videoId: 'vid-ielts-speaking',
      segmentId: 'seg-ielts-5',
      type: 'vocabulary',
      question: 'Từ "indispensable" mang ý nghĩa gì?',
      options: ['Không quan trọng lắm', 'Không thể thiếu / Tuyệt đối cần thiết', 'Tốn kém chi phí', 'Khó khăn khi thực hiện'],
      correctAnswerIndex: 1,
      explanation: 'Indispensable = absolutely necessary / essential (không thể thiếu).',
    },
  ],
  'vid-business-pitch': [
    {
      id: 'quiz-bp-1',
      videoId: 'vid-business-pitch',
      segmentId: 'seg-bp-2',
      type: 'meaning',
      question: 'Cụm từ "operational efficiency" trong ngữ cảnh kinh doanh có nghĩa là gì?',
      options: ['Chi phí quản lý doanh nghiệp', 'Hiệu quả hoạt động / vận hành', 'Tốc độ sản xuất hàng hóa', 'Chiêu thức tiếp thị'],
      correctAnswerIndex: 1,
      explanation: 'Operational efficiency là hiệu quả hoạt động/vận hành doanh nghiệp.',
    },
  ],
  'vid-daily-conversation': [
    {
      id: 'quiz-dc-1',
      videoId: 'vid-daily-conversation',
      segmentId: 'seg-dc-1',
      type: 'meaning',
      question: 'Cụm từ "reservation under your name" dùng để hỏi điều gì?',
      options: ['Tên đầy đủ của bạn', 'Việc đặt bàn trước dưới tên của bạn', 'Địa chỉ email đặt hàng', 'Số thẻ tín dụng thanh toán'],
      correctAnswerIndex: 1,
      explanation: 'Reservation under your name có nghĩa là bàn đặt trước dưới tên bạn.',
    },
  ],
};
